<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Images\**" />
    <Compile Remove="kepek\**" />
    <EmbeddedResource Remove="Images\**" />
    <EmbeddedResource Remove="kepek\**" />
    <None Remove="Images\**" />
    <None Remove="kepek\**" />
    <Page Remove="Images\**" />
    <Page Remove="kepek\**" />
  </ItemGroup>

</Project>
